baseURL: https://tehuel.github.io/bennugd-redesign/
title: BennuGD
paginate: 6

params:
  mainSections:
    - blog
  repository: https://github.com/tehuel/bennugd-redesign/

outputs:
  home:
  - HTML
  - RSS
  - JSON
  page:
  - HTML
