baseURL = "https://tehuel.github.io/bennugd-redesign/"
title = "BennuGD"
paginate = 6
theme = "divhub-website-theme"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[params]
  mainSections = ["blog"]
  repository = "https://github.com/tehuel/bennugd-redesign/"
  tagline = "A multi-platform div-like videogame programming language."
  donations = "https://paypal.com"
  logo = "img/logo.png"
  logo_small = "img/logo.png"
  [params.colors]
    dark_mode = false
    primary = "#CF9E61"
    text = "#38362b"
    link = "#a54d0e"
    bg = "#ffffee"
    footer = "#cebea7"
