baseURL = 'https://divhub.github.io/bennugd-website/'
languageCode = 'en-us'
title = 'BennuGD'
theme = 'hextra'

disableKinds = ['taxonomy', 'term']

[params.page]
  width = 'normal'

[params.footer]
  width = 'normal'

[params.navbar]
  width = 'normal'

[params.navbar.logo]
  path = 'img/logo.png'

[params.editURL]
  enable = true
  base = 'https://github.com/DivHub/bennugd-website/edit/master/content'

[menu]
[[menu.main]]
    name = 'Search'
    [menu.main.params]
      type = 'search'

[[menu.sidebar]]
  identifier = "more"
  name = "Community"
  weight = 1
  [menu.sidebar.params]
    type = "separator"
[[menu.sidebar]]
  identifier = "Discord"
  name = "Discord ↗"
  url = "https://discord.gg/CAKr9QR"
  weight = 2
[[menu.sidebar]]
  identifier = "Forum"
  name = "Forum ↗"
  url = "https://forum.bennugd.org/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.parser.attribute]
	block = true
